### ISSUE TITLE
关于用户进程

### ISSUE THREAD

**Issue by Eric217** [Eric217/OS_EXP#1]
一直测试用户进程只测试一两行，也一直表现正常。但是今天突然发现再多写一行就缺页异常at 0xB80A0。不知道从哪个版本开始的，我是真的烦

**Comment by Eric217** [comment]
我刚回退到几天以前的进程版本，再运行，直接栈溢出了😭😭😭😭 鼓捣了一晚上，结果坏起来了😭
打游戏去了😭😭

**Comment by Eric217** [comment]
今天突然想起来 0xb8000是显存段，中午去看看。
现在用的都是虚拟内存，访问显存应该是 0xc00b800

**Comment by Eric217** [comment]
今天晚上花了挺多时间的。主要收获：真正脱离课本，上阵熟悉了 bochs 常用调试方式。
关于今天发现的两个bug，
bug 一：
这个bug出现的时机很巧妙：屏幕当时恰好还有一行的显示空间就该滚屏了（debug前我肯定没注意这个）。
当时还想到 A0 是 160，一行是 80个字符。
首先看见 0xB80A0 缺页就直接想到访问显存时缺页，但是凭什么是 A0？？？还有内核线程怎么用都不出错啊，用户进程tmd竟然还能显示一行，第二行就出错了？
经过debug，发现了出错的命令：movsd （当前滚屏实现是搬运显存，而不是通过读写显卡寄存器）
个人理解：
当前特权级为0，gs 可以访问，因此可以打印出字符；滚屏操作时，b8000,b80a0 写入 edi,esi 由于此时为用户进程，只共享内核的 768～1024 页目录项，所以直接访问 b80a0 会缺页。
bug 二：
一时糊涂 0xC0000000 作为 int 参与了比较，这个数最高位为1，应该强转为 uint32 再比较。

**Comment by zhuheqqq** [comment]
> 今天晚上花了挺多时间的。主要收获：真正脱离课本，上阵熟悉了 bochs 常用调试方式。 关于今天发现的两个bug， bug 一： 这个bug出现的时机很巧妙：屏幕当时恰好还有一行的显示空间就该滚屏了（debug前我肯定没注意这个）。 当时还想到 A0 是 160，一行是 80个字符。 首先看见 0xB80A0 缺页就直接想到访问显存时缺页，但是凭什么是 A0？？？还有内核线程怎么用都不出错啊，用户进程tmd竟然还能显示一行，第二行就出错了？ 经过debug，发现了出错的命令：movsd （当前滚屏实现是搬运显存，而不是通过读写显卡寄存器） 个人理解： 当前特权级为0，gs 可以访问，因此可以打印出字符；滚屏操作时，b8000,b80a0 写入 edi,esi 由于此时为用户进程，只共享内核的 768～1024 页目录项，所以直接访问 b80a0 会缺页。 bug 二： 一时糊涂 0xC0000000 作为 int 参与了比较，这个数最高位为1，应该强转为 uint32 再比较。

我最近正在写这个也碰到这个问题，非常感谢你
